name: HidenChest
version: '${project.version}'
main: me.hydraplugins.hidenchest.HidenChest
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10
main: me.hydraplugins.hidenchest.HidenChest
authors: [SpreestDev]
commands:
    HidenChest:
        usage: /<command>

